Use course object to fix lms test failure
This test fails in LMS:

$ tox -e pytest lms/djangoapps/course_api/tests/test_views.py::CourseListSearchViewTest::test_list_all_with_search_term
ValueError: Unknown action for object type '<class 'opaque_keys.edx.locator.CourseLocator'>': 'see_in_catalog'

see_in_catalog expects a course object

This reverts 3192723d13c4183a80663b38a6851c9992dc770f , because it was
the offending commit.